#!/bin/bash
set -e

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}Starting Dolibarr Docker Container...${NC}"

# Function to wait for database
wait_for_db() {
    echo -e "${YELLOW}Waiting for database connection...${NC}"
    maxcounter=60
    counter=1
    while ! mysql -h"${DOLI_DB_HOST}" -P"${DOLI_DB_PORT}" -u"${DOLI_DB_USER}" -p"${DOLI_DB_PASSWORD}" -e "show databases;" > /dev/null 2>&1; do
        sleep 2
        counter=`expr $counter + 1`
        if [ $counter -gt $maxcounter ]; then
            >&2 echo -e "${RED}Failed to connect to database after ${maxcounter} attempts${NC}"
            exit 1
        fi;
        echo "Waiting for database... (attempt $counter/$maxcounter)"
    done
    echo -e "${GREEN}Database is ready!${NC}"
}

# Update PHP configuration
echo -e "${YELLOW}Updating PHP configuration...${NC}"
if [ -n "${PHP_INI_DATE_TIMEZONE}" ]; then
    echo "date.timezone = ${PHP_INI_DATE_TIMEZONE}" > ${PHP_INI_DIR}/conf.d/dolibarr-timezone.ini
fi
if [ -n "${PHP_INI_MEMORY_LIMIT}" ]; then
    echo "memory_limit = ${PHP_INI_MEMORY_LIMIT}" > ${PHP_INI_DIR}/conf.d/dolibarr-memory.ini
fi
if [ -n "${PHP_INI_UPLOAD_MAX_FILESIZE}" ]; then
    echo "upload_max_filesize = ${PHP_INI_UPLOAD_MAX_FILESIZE}" > ${PHP_INI_DIR}/conf.d/dolibarr-upload.ini
fi
if [ -n "${PHP_INI_POST_MAX_SIZE}" ]; then
    echo "post_max_size = ${PHP_INI_POST_MAX_SIZE}" > ${PHP_INI_DIR}/conf.d/dolibarr-post.ini
fi

# Fix permissions if HOST_USER_ID is provided
if [ -n "${HOST_USER_ID}" ] && [ -n "${HOST_GROUP_ID}" ]; then
    echo -e "${YELLOW}Adjusting permissions for user ${HOST_USER_ID}:${HOST_GROUP_ID}...${NC}"
    usermod -u "${HOST_USER_ID}" www-data 2>/dev/null || true
    groupmod -g "${HOST_GROUP_ID}" www-data 2>/dev/null || true
fi

# Ensure directories exist with proper permissions
echo -e "${YELLOW}Setting up directories and permissions...${NC}"
mkdir -p /var/www/documents
mkdir -p /var/www/html/htdocs/conf
mkdir -p /var/www/html/htdocs/custom

# Set ownership and permissions
chown -R www-data:www-data /var/www/documents
chown -R www-data:www-data /var/www/html/htdocs/conf
chown -R www-data:www-data /var/www/html/htdocs/custom
chmod -R 775 /var/www/documents
chmod -R 775 /var/www/html/htdocs/conf
chmod -R 775 /var/www/html/htdocs/custom

# Create conf.php if it doesn't exist and auto-install is enabled
CONF_FILE="/var/www/html/htdocs/conf/conf.php"
if [ ! -f "$CONF_FILE" ] && [ "${DOLI_INSTALL_AUTO}" = "1" ]; then
    echo -e "${YELLOW}Auto-configuring Dolibarr...${NC}"
    
    # Wait for database to be ready
    wait_for_db
    
    # Create conf.php
    cat > "$CONF_FILE" <<EOF
<?php
//
// File generated by Dolibarr Docker installation
//
// Take a look at conf.php.example

// Main parameters
\$dolibarr_main_url_root='${DOLI_URL_ROOT}';
\$dolibarr_main_document_root='/var/www/html/htdocs';
\$dolibarr_main_url_root_alt='/custom';
\$dolibarr_main_document_root_alt='/var/www/html/htdocs/custom';
\$dolibarr_main_data_root='/var/www/documents';
\$dolibarr_main_db_host='${DOLI_DB_HOST}';
\$dolibarr_main_db_port='${DOLI_DB_PORT}';
\$dolibarr_main_db_name='${DOLI_DB_NAME}';
\$dolibarr_main_db_prefix='llx_';
\$dolibarr_main_db_user='${DOLI_DB_USER}';
\$dolibarr_main_db_pass='${DOLI_DB_PASSWORD}';
\$dolibarr_main_db_type='${DOLI_DB_TYPE}';
\$dolibarr_main_db_character_set='utf8';
\$dolibarr_main_db_collation='utf8_unicode_ci';

// Security
\$dolibarr_main_authentication='dolibarr';
\$dolibarr_main_prod='0';
\$dolibarr_main_force_https='0';
\$dolibarr_main_restrict_os_commands='mysqldump, mysql, pg_dump, pgrestore';
\$dolibarr_nocsrfcheck='${DOLI_NOCSRFCHECK}';
\$dolibarr_main_instance_unique_id='$(openssl rand -hex 16)';
\$dolibarr_mailing_limit_sendbyweb='0';

// Development mode
\$dolibarr_main_dev='${DOLI_DEV_MODE}';
EOF
    
    chown www-data:www-data "$CONF_FILE"
    chmod 400 "$CONF_FILE"
    
    # Create install.lock file to indicate installation is complete
    touch /var/www/html/htdocs/install/install.lock
    chown www-data:www-data /var/www/html/htdocs/install/install.lock
    chmod 400 /var/www/html/htdocs/install/install.lock
    
    echo -e "${GREEN}Dolibarr configuration complete!${NC}"
    echo -e "${GREEN}You can access Dolibarr at: ${DOLI_URL_ROOT}${NC}"
    echo -e "${GREEN}Default admin login: ${DOLI_ADMIN_LOGIN}${NC}"
    echo -e "${GREEN}Default admin password: ${DOLI_ADMIN_PASSWORD}${NC}"
    
elif [ ! -f "$CONF_FILE" ]; then
    echo -e "${YELLOW}No configuration file found. Please complete installation at:${NC}"
    echo -e "${YELLOW}${DOLI_URL_ROOT}/install${NC}"
else
    echo -e "${GREEN}Configuration file exists. Skipping auto-configuration.${NC}"
fi

# Run database fixes if database is accessible
if [ -n "${DOLI_DB_HOST}" ] && [ -n "${DOLI_DB_USER}" ] && [ -n "${DOLI_DB_PASSWORD}" ]; then
    echo -e "${YELLOW}Checking database and applying fixes...${NC}"
    
    # Wait for database to be ready
    maxcounter=30
    counter=1
    while ! mysql -h"${DOLI_DB_HOST}" -P"${DOLI_DB_PORT:-3306}" -u"${DOLI_DB_USER}" -p"${DOLI_DB_PASSWORD}" "${DOLI_DB_NAME}" -e "SELECT 1" > /dev/null 2>&1; do
        sleep 1
        counter=`expr $counter + 1`
        if [ $counter -gt $maxcounter ]; then
            echo -e "${YELLOW}Database not ready, skipping fixes${NC}"
            break
        fi
    done
    
    if [ $counter -le $maxcounter ]; then
        # Apply database fixes if file exists
        if [ -f /var/www/html/init-db-fixes.sql ]; then
            echo -e "${YELLOW}Applying database fixes...${NC}"
            mysql -h"${DOLI_DB_HOST}" -P"${DOLI_DB_PORT:-3306}" -u"${DOLI_DB_USER}" -p"${DOLI_DB_PASSWORD}" "${DOLI_DB_NAME}" < /var/www/html/init-db-fixes.sql 2>/dev/null || true
            echo -e "${GREEN}Database fixes applied${NC}"
        fi
    fi
fi

# Enable development mode if requested
if [ "${DOLI_DEV_MODE}" = "1" ]; then
    echo -e "${YELLOW}Enabling development mode...${NC}"
    echo "display_errors = On" > ${PHP_INI_DIR}/conf.d/dolibarr-dev.ini
    echo "display_startup_errors = On" >> ${PHP_INI_DIR}/conf.d/dolibarr-dev.ini
    echo "error_reporting = E_ALL" >> ${PHP_INI_DIR}/conf.d/dolibarr-dev.ini
fi

# Configure Apache document root
if [ -n "${APACHE_DOCUMENT_ROOT}" ]; then
    echo -e "${YELLOW}Setting Apache document root to ${APACHE_DOCUMENT_ROOT}${NC}"
    sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
    sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf
fi

echo -e "${GREEN}Container initialization complete. Starting Apache...${NC}"

# Execute the main command
exec "$@"
