<?php
//
// File generated by Dolibarr Docker installation
//
// Take a look at conf.php.example

// Main parameters
$dolibarr_main_url_root='http://localhost:8080';
$dolibarr_main_document_root='/var/www/html/htdocs';
$dolibarr_main_url_root_alt='/custom';
$dolibarr_main_document_root_alt='/var/www/html/htdocs/custom';
$dolibarr_main_data_root='/var/www/documents';
$dolibarr_main_db_host='mariadb';
$dolibarr_main_db_port='3306';
$dolibarr_main_db_name='dolibarr';
$dolibarr_main_db_prefix='llx_';
$dolibarr_main_db_user='dolibarr';
$dolibarr_main_db_pass='dolibarr_pwd';
$dolibarr_main_db_type='mysqli';
$dolibarr_main_db_character_set='utf8';
$dolibarr_main_db_collation='utf8_unicode_ci';

// Security
$dolibarr_main_authentication='dolibarr';
$dolibarr_main_prod='0';
$dolibarr_main_force_https='0';
$dolibarr_main_restrict_os_commands='mysqldump, mysql, pg_dump, pgrestore';
$dolibarr_nocsrfcheck='0';
$dolibarr_main_instance_unique_id='2990841c61267e495e17dc00cf6cbbbc';
$dolibarr_mailing_limit_sendbyweb='0';

// Development mode
$dolibarr_main_dev='0';
